from flask_babel import _

error_msgs = [_(
    '500 Internal Server Error: The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.')
              ]
countries = [_("Afghanistan"),
             _("Albania"),
             _("Algeria"),
             _("Andorra"),
             _("American Samoa"),
             _("Angola"),
             _("Anguilla"),
             _("Antartica"),
             _("Antigua and Barbuda"),
             _("Argentina"),
             _("Armenia"),
             _("Aruba"),
             _("Ashmore and Cartier Island"),
             _("Australia"),
             _("Austria"),
             _("Azerbaijan"),
             _("Bahamas"),
             _("Bahrain"),
             _("Bangladesh"),
             _("Barbados"),
             _("Belarus"),
             _("Belgium"),
             _("Belize"),
             _("Benin"),
             _("Bermuda"),
             _("Bhutan"),
             _("Bolivia"),
             _("Bosnia and Herzegovina"),
             _("Botswana"),
             _("Brazil"),
             _("British Virgin Islands"),
             _("Brunei"),
             _("Bulgaria"),
             _("Burkina Faso"),
             _("Burma"),
             _("Burundi"),
             _("Cambodia"),
             _("Cameroon"),
             _("Canada"),
             _("Cape Verde"),
             _("Cayman Islands"),
             _("Central African Republic"),
             _("Chad"),
             _("Chile"),
             _("China"),
             _("Christmas Island"),
             _("Clipperton Island"),
             _("Cocos (Keeling) Islands"),
             _("Colombia"),
             _("Comoros"),
             _("Congo"),
             _("Cook Islands"),
             _("Costa Rica"),
             _("Cote dIvoire"),
             _("Croatia"),
             _("Cuba"),
             _("Cyprus"),
             _("Czeck Republic"),
             _("Denmark"),
             _("Djibouti"),
             _("Dominica"),
             _("Dominican Republic"),
             _("Ecuador"),
             _("Egypt"),
             _("El Salvador"),
             _("Equatorial Guinea"),
             _("Eritrea"),
             _("Estonia"),
             _("Ethiopia"),
             _("Europa Island"),
             _("Falkland Islands (Islas Malvinas)"),
             _("Faroe Islands"),
             _("Fiji"),
             _("Finland"),
             _("France"),
             _("French Guiana"),
             _("French Polynesia"),
             _("French Southern and Antarctic Lands"),
             _("Gabon"),
             _("Gambia"),
             _("Gaza Strip"),
             _("Georgia"),
             _("Germany"),
             _("Ghana"),
             _("Gibraltar"),
             _("Glorioso Islands"),
             _("Greece"),
             _("Greenland"),
             _("Grenada"),
             _("Guadeloupe"),
             _("Guam"),
             _("Guatemala"),
             _("Guernsey"),
             _("Guinea"),
             _("Guinea-Bissau"),
             _("Guyana"),
             _("Haiti"),
             _("Heard Island and McDonald Islands"),
             _("Holy See (Vatican City)"),
             _("Honduras"),
             _("Hong Kong"),
             _("Howland Island"),
             _("Hungary"),
             _("Iceland"),
             _("India"),
             _("Indonesia"),
             _("Iran"),
             _("Iraq"),
             _("Ireland"),
             _("Israel"),
             _("Italy"),
             _("Jamaica"),
             _("Jan Mayen"),
             _("Japan"),
             _("Jarvis Island"),
             _("Jersey"),
             _("Johnston Atoll"),
             _("Jordan"),
             _("Juan de Nova Island"),
             _("Kazakhstan"),
             _("Kenya"),
             _("Kiribati"),
             _("Korea North"),
             _("Korea South"),
             _("Kuwait"),
             _("Kyrgyzstan"),
             _("Laos"),
             _("Latvia"),
             _("Lebanon"),
             _("Lesotho"),
             _("Liberia"),
             _("Libya"),
             _("Liechtenstein"),
             _("Lithuania"),
             _("Luxembourg"),
             _("Macau"),
             _("Macedonia"),
             _("Madagascar"),
             _("Malawi"),
             _("Malaysia"),
             _("Maldives"),
             _("Mali"),
             _("Malta"),
             _("Man Isle of"),
             _("Marshall Islands"),
             _("Martinique"),
             _("Mauritania"),
             _("Mauritius"),
             _("Mayotte"),
             _("Mexico"),
             _("Micronesia"),
             _("Midway Islands"),
             _("Moldova"),
             _("Monaco"),
             _("Mongolia"),
             _("Montserrat"),
             _("Morocco"),
             _("Mozambique"),
             _("Namibia"),
             _("Nauru"),
             _("Nepal"),
             _("Netherlands"),
             _("Netherlands Antilles"),
             _("New Caledonia"),
             _("New Zealand"),
             _("Nicaragua"),
             _("Niger"),
             _("Nigeria"),
             _("Niue"),
             _("Norfolk Island"),
             _("No Man`s Island"),
             _("Northern Mariana Islands"),
             _("Norway"),
             _("Oman"),
             _("Pakistan"),
             _("Palau"),
             _("Panama"),
             _("Papua New Guinea"),
             _("Paraguay"),
             _("Peru"),
             _("Philippines"),
             _("Pitcaim Islands"),
             _("Poland"),
             _("Portugal"),
             _("Puerto Rico"),
             _("Qatar"),
             _("Reunion"),
             _("Romainia"),
             _("Russia"),
             _("Rwanda"),
             _("Saint Helena"),
             _("Saint Kitts and Nevis"),
             _("Saint Lucia"),
             _("Saint Pierre and Miquelon"),
             _("Saint Vincent and the Grenadines"),
             _("Samoa"),
             _("San Marino"),
             _("Sao Tome and Principe"),
             _("Saudi Arabia"),
             _("Scotland"),
             _("Senegal"),
             _("Serbia and Monterago"),
             _("Seychelles"),
             _("Sierra Leone"),
             _("Singapore"),
             _("Slovakia"),
             _("Slovenia"),
             _("Solomon Islands"),
             _("Somalia"),
             _("South Africa"),
             _("South Georgia and the South Sandwich Islandss"),
             _("Spain"),
             _("Spratly Islands"),
             _("SriLanka"),
             _("Sudan"),
             _("Suriname"),
             _("Svalbard"),
             _("Swaziland"),
             _("Sweden"),
             _("Switzerland"),
             _("Syria"),
             _("Taiwan"),
             _("Tajikistan"),
             _("Tanzania"),
             _("Thailand"),
             _("Trinidad and Tobago"),
             _("Toga"),
             _("Tokelau"),
             _("Tonga"),
             _("Tunisia"),
             _("Turkey"),
             _("Turkmenistan"),
             _("Turks and Caicos Island"),
             _("Tuvalu"),
             _("Uganda"),
             _("Ukraine"),
             _("United Arab Emirates"),
             _("United Kingdom"),
             _("Uruguay"),
             _("United States"),
             _("Uzbekistan"),
             _("Vanuatu"),
             _("Venezuela"),
             _("Vietnam"),
             _("Virgin Islands"),
             _("Wales"),
             _("Wallis and Futuna"),
             _("West Bank"),
             _("Western Sahara"),
             _("Yemen"),
             _("Yugoslavia"),
             _("Zambia"),
             _("Zimbabwe")]
